name: aplikasi_manajemen_event_dan_tiket_digital
description: "Aplikasi manajemen event dan tiket digital dengan Flutter"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  
  # SQLite Database (Storage Utama)
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  
  # Session Management (Lightweight)
  shared_preferences: ^2.2.2
  
  # Date & Time Formatting
  intl: ^0.19.0
  
  # QR Code Generation & Scanning
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.3
  
  # PDF Generation & Printing
  pdf: ^3.11.1
  printing: ^5.13.3
  
  # Permissions Handler
  permission_handler: ^11.3.1
  
  # State Management (opsional tapi direkomendasikan)
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true